apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api
  namespace: demo
  labels:
    app: api
spec:
  replicas: 4

  selector:
    matchLabels:
      app: api

  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause:
          duration: 30s
      - analysis:
          templates:
          - templateName: api-success-rate
      - setWeight: 50
      - pause:
          duration: 30s
      - analysis:
          templates:
          - templateName: api-success-rate
      - setWeight: 100

  template:
    metadata:
      labels:
        app: api
        owner: phuong
    spec:
      containers:
      - name: api
        image: ghcr.io/tieuphuong1711/w10-lab-lan2-api:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: v1
        - name: ERROR_RATE
          value: "0"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080


#sau khi có analysis template rồi thì mới gọi vào rollout

#nếu ko thêm analysis template vào rollout thì nó sẽ chạy rollout bình thường, ko có phân tích gì cả            