#Child app này dùng ArgoCD để cài kube-prometheus-stack bằng Helm
# app-api/servicemonitor.yaml
# → lỗi vì chưa có ServiceMonitor CRD

# app-alert/prometheus-rules.yaml
# → lỗi vì chưa có PrometheusRule CRD

# app-analysis/analysis-template.yaml
# → query Prometheus không có nơi để query

# CRD = dạy Kubernetes hiểu loại YAML mới

# Prometheus Operator
# → dạy Kubernetes hiểu ServiceMonitor, PrometheusRule

# Argo Rollouts
# → dạy Kubernetes hiểu Rollout, AnalysisTemplate

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 66.2.1
    helm:
      values: |
        grafana:
          enabled: true

        prometheus:
          enabled: true

        alertmanager:
          enabled: true
          config:
            global:
              smtp_smarthost: 'smtp.gmail.com:587'
              smtp_from: 'your-email@gmail.com'
              smtp_auth_username: 'your-email@gmail.com'
              smtp_auth_password: 'your-gmail-app-password'
              smtp_require_tls: true

            route:
              receiver: email-alert

            receivers:
            - name: email-alert
              email_configs:
              - to: 'your-email@gmail.com'
                send_resolved: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true