name: Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase owner
        run: |
          echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build \
            -t ghcr.io/${{ env.OWNER_LC }}/w10-lab-lan2-api:${{ github.sha }} \
            -t ghcr.io/${{ env.OWNER_LC }}/w10-lab-lan2-api:v1 \
            ./src/api

      - name: Push Image
        run: |
          docker push ghcr.io/${{ env.OWNER_LC }}/w10-lab-lan2-api:${{ github.sha }}
          docker push ghcr.io/${{ env.OWNER_LC }}/w10-lab-lan2-api:v1

      - name: Update Rollout Image
        run: |
          sed -i "s|image: .*|image: ghcr.io/${{ env.OWNER_LC }}/w10-lab-lan2-api:v1|g" app-api/rollout.yaml

      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add app-api/rollout.yaml
          git commit -m "update image to v1" || true
          git push