apiVersion: v1
kind: Secret
metadata:
name: alertmanager-email
namespace: monitoring
type: Opaque
stringData:
smtp_username: tp17112k4@gmail.com
smtp_password: zyaa gubc ttjo uwck
smtp_from: tp17112k4@gmail.com
